single and last functions
sj-freitas/forofa pull request #13
Opened 2018-10-10 10:58 UTC by RubenMateus

## Motivation and Context
Add new useful methods(single/last)
PR came from issue: https://github.com/sj-freitas/forofa/issues/3
 ## How Has This Been Tested?
Added 100% test coverage to the new added functions and all existing tests passed.
 ## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 ## Checklist:
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2018-10-10 11:15 UTC, RubenMateus commented
Missing alter package-json for the version.

2018-10-10 20:51 UTC, sj-freitas requested changes
Some minor changes, also, add the documentation to the functions README.MD.

2018-10-10 20:51 UTC, sj-freitas commented on lib/functions/index.js
> +  last,
Although undocumented, these are all in alphabetic order, it would be nice to keep this pattern.

2018-10-10 20:51 UTC, sj-freitas commented on lib/functions/last.js
> +  if (!lastValue) {
Instead of doing this check, I'd suggest using a count or a flag, since the lastValue can be by itself `null`or `undefined`, `""`, etc.

2018-10-10 20:51 UTC, sj-freitas commented on lib/functions/last.js
> +    throw new Error("There's no element!");
The .NET message is: 
> Sequence contains no elements

https://dotnetfiddle.net/L4RBfj

2018-10-10 20:51 UTC, sj-freitas commented on lib/functions/single.js
> +    throw new Error("There's no element!");
Change this message to:
> Sequence contains no elements

2018-10-10 20:51 UTC, sj-freitas commented on lib/functions/single.js
> +  const nextObj = iterator.next();
Why not use destructuring of the `{ done }` value? Give it a different name to avoid issues with the constant created before.

2018-10-10 20:51 UTC, sj-freitas commented on lib/functions/single.js
> +    throw new Error("There's more than 1 element!");
Change the message to:
> Sequence contains more than one element

https://dotnetfiddle.net/jS3sLV

2018-10-12 13:58 UTC, sj-freitas approved these changes
Just a very very small change, everything else is pretty good! :+1:

2018-10-12 13:58 UTC, sj-freitas commented on lib/functions/README.md
> +**Warning**: If more than 1 match, it'll throw an error.
Add a warning 
> if the collection is infinite and it has a predicate that is fulfilled just once, it can block your code.

2018-10-13 12:49 UTC, merged